### ISSUE TITLE
Does not run for me. Crashes on start

### ISSUE THREAD

**Issue by burhanuday** [hl3hl3/ARCoreMeasure#3]
`2018-11-05 20:47:00.819 19097-19097/com.hl3hl3.arcoremeasure E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hl3hl3.arcoremeasure, PID: 19097
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.surfaceCreated()' on a null object reference
        at android.opengl.GLSurfaceView.surfaceCreated(GLSurfaceView.java:524)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:624)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2245)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6399)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
        at android.view.Choreographer.doCallbacks(Choreographer.java:685)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)`

**Comment by GotmareDamini** [comment]
2019-06-23 07:20:01.493 5777-5777/com.example.gallery_dg E/HAL: PATH3 /odm/lib64/hw/gralloc.qcom.so
2019-06-23 07:20:01.494 5777-5777/com.example.gallery_dg E/HAL: PATH2 /vendor/lib64/hw/gralloc.qcom.so
2019-06-23 07:20:01.494 5777-5777/com.example.gallery_dg E/HAL: PATH1 /system/lib64/hw/gralloc.qcom.so
2019-06-23 07:20:01.494 5777-5777/com.example.gallery_dg E/HAL: PATH3 /odm/lib64/hw/gralloc.msm8953.so
2019-06-23 07:20:01.494 5777-5777/com.example.gallery_dg E/HAL: PATH2 /vendor/lib64/hw/gralloc.msm8953.so
2019-06-23 07:20:01.494 5777-5777/com.example.gallery_dg E/HAL: PATH1 /system/lib64/hw/gralloc.msm8953.so
2019-06-23 07:20:01.582 5777-5829/com.example.gallery_dg I/Adreno: QUALCOMM build                   : 01d2d27, I3d52eaf367
    Build Date                       : 12/10/16
    OpenGL ES Shader Compiler Version: XE031.09.00.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-06-23 07:20:01.587 5777-5829/com.example.gallery_dg I/OpenGLRenderer: Initialized EGL, version 1.4
2019-06-23 07:20:01.587 5777-5829/com.example.gallery_dg D/OpenGLRenderer: Swap behavior 1
2019-06-23 07:20:01.633 5777-5777/com.example.gallery_dg D/AndroidRuntime: Shutting down VM
2019-06-23 07:20:01.642 5777-5777/com.example.gallery_dg E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gallery_dg, PID: 5777
    java.lang.RuntimeException: Canvas: trying to draw too large(144000000bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1286)
        at android.view.View.draw(View.java:17099)
        at android.view.View.updateDisplayListIfDirty(View.java:16081)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.draw(View.java:17102)
        at android.view.View.updateDisplayListIfDirty(View.java:16081)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.draw(View.java:17102)
        at android.widget.ScrollView.draw(ScrollView.java:1722)
        at android.view.View.updateDisplayListIfDirty(View.java:16081)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16865)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
        at android.view.View.draw(View.java:17102)
        at com.android.internal.policy.DecorView.draw(DecorView.java:754)
        at android.view.View.updateDisplayListIfDirty(View.java:16081)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2648)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2255)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
2019-06-23 07:20:01.643 5777-5777/com.example.gallery_dg E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6399)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
        at android.view.Choreographer.doCallbacks(Choreographer.java:685)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
